
// Get All Cars
GET http://localhost:5000/cars
 
###

// Get Car by Id
GET http://localhost:5000/cars/9


###
// Create Car
POST http://localhost:5000/cars
Content-Type: application/json

  {
    "band":"Mitsubishi",
    "model":"ASX",
    "yearProd":2015
  }

###

// Update car
PUT http://localhost:5000/cars/1
Content-Type: application/json

  {
    "idCar":1,
    "band":"VolksWagen",
    "model":"Polo",
    "yearProd":2022
  }

###
// Delete car
DELETE http://localhost:5000/cars/8