
// Get All Cars
GET http://localhost:5000/cars
 
###

// Get Car by Id
GET http://localhost:5000/cars/1


###
// Create Car
POST http://localhost:5000/cars
Content-Type: application/json

  {
    "band":"KIA",
    "model":"Sportage",
    "yearProd":2010
  }

###

// Update car
PUT http://localhost:5000/cars/1
Content-Type: application/json

  {
    "idCar":1,
    "band":"Jeep",
    "model":"Compass",
    "yearProd":2020
  }

